[package]
name = "chessbackend"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 0

[dependencies]
actix-web = "4.3.1"
shuttle-actix-web = "0.29.0"
shuttle-runtime = "0.29.0"
tokio = "1.26.0"
rand = "0.8.4"
